version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    insecure-external-code-execution: allow
    commit-message:
      prefix: "deps(elixir):"
